# Generated by Django 4.2.6 on 2024-02-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(max_length=50, upload_to="portfolio/images/"),
        ),
    ]
